sudo: required

tags: true

services:
- docker

script:
- docker run --rm -v "$PWD":/go/src/gohaqd -w /go/src/gohaqd -e 'CGO_ENABLED=0' -e 'GOOS=linux' golang:1.7 /bin/bash -c "go build -a -v -ldflags '-w'"

after_success:
- export REPO=$TRAVIS_REPO_SLUG
- export TAG=${TRAVIS_TAG:=latest}
- docker build -t $REPO:$TRAVIS_COMMIT .
- docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push $REPO

